use super::{capability_runtime, definition_revisions, handlers, state::AnalyticsState};
use axum::{Router, middleware, routing::get};

pub(crate) fn router(state: AnalyticsState) -> Router {
    state.capabilities.spawn();
    Router::new()
        .route(
            "/v1/sites/{site_id}/definition-revisions",
            get(definition_revisions::get_definition_revisions),
        )
        .route(
            "/v1/sites/{site_id}/overview",
            get(handlers::overview::overview),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/overview",
            get(handlers::reports::range_overview),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/timeline",
            get(handlers::reports::timeline),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/pages",
            get(handlers::reports::pages),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/conversions",
            get(handlers::reports::conversions),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/funnels",
            get(handlers::reports::funnels),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/web-vitals",
            get(handlers::reports::web_vitals),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/geo",
            get(handlers::geo::countries),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/events",
            get(handlers::reports::events),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/visitors",
            get(handlers::audience_dimension_reports::visitors),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/sessions",
            get(handlers::audience_dimension_reports::sessions),
        )
        .route(
            "/v1/sites/{site_id}/reports/{from}/{to}/dimensions/{dimension}",
            get(handlers::audience_dimension_reports::dimensions),
        )
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            capability_runtime::gate,
        ))
        .with_state(state)
}
